QA test updates. Fix location of fsstress and clamp the uid/gid range for chown so as to limit memory requirements for xfs_db/check afterward.

diff --git a/013 b/013
--- a/013
+++ b/013
@@ -86,7 +86,8 @@ _do_test()
     echo "fsstress.$_n : $_param"
     echo "-----------------------------------------------"
     # -v >$tmp.out
-    if ! $here/src/fsstress $_param $FSSTRESS_AVOID -n $_count -d $out >/dev/null 2>&1
+    # -m limits number of users/groups so check doesn't fail (malloc) later
+    if ! $here/ltp/fsstress $_param $FSSTRESS_AVOID -m 8 -n $_count -d $out >/dev/null 2>&1
     then
         echo "    fsstress (count=$_count) returned $? - see $seq.full"
         
