Merge of xfs-cmds-2.4.18:slinx:111140a by nathans.
  minor changes to xfstests as we transition to new EA/ACL interfaces.

diff --git a/020 b/020
--- a/020
+++ b/020
@@ -67,50 +67,29 @@ _attr()
     return $exit
 }
 
+_getfattr()
+{
+    getfattr $* 2>$tmp.err >$tmp.out
+    exit=$?
+    _filter $tmp.out
+    _filter $tmp.err 1>&2
+    return $exit
+}
+
 _attr_list()
 {
     file=$1
     
     echo "   *** print attributes"
-    if ! _attr -l $file >$tmp.raw
+    if ! _getfattr -ad $file >$tmp.raw
     then
         echo "      !!! error return"
         return 1
     fi
-    
-    $AWK_PROG -v file=$file '
-        {
-            print substr($2,2,length($2)-2)
-            count++
-        }
-        END { 
-            exit count 
-        }
-        ' <$tmp.raw >$tmp.list
-        
-    echo "      *** $? attribute(s)"
-    for l in `cat $tmp.list`
-    do
-        if ! _attr -g $l $file >$tmp.raw
-        then
-            echo "         *** $l"
-            echo "         !!! error return"
-            return 1
-        fi
-        $AWK_PROG '
-            NR==1 {
-                print "         *** field: " substr($2,2,length($2)-2) \
-                      " length: " $5
-                next
-            }
-            {
-                print "            ::: " $0
-            }
-        ' <$tmp.raw
-        
-    done
 }
 
+[ -x /usr/bin/attr ] || _notrun "attr is not installed"
+[ -x /usr/bin/getfattr ] || _notrun "getfattr is not installed"
 
 # real QA test starts here
 
@@ -161,8 +140,8 @@ done
 
 echo "*** check"
 # don't print it all out...
-attr -l $testfile \
-    | $AWK_PROG '{ l++ } END {print "   *** " l " attribute(s)" }'
+getfattr $testfile \
+    | $AWK_PROG '{ l++ } END {print "   *** " (l - 1) " attribute(s)" }'
 
 echo "*** remove lots of attributes"
 v=0
@@ -170,7 +149,7 @@ while [ $v -lt 1000 ]
 do
     if ! attr -r "attribute_$v" $testfile >/dev/null
     then
-        echo "!!! failed to add \"attribute_$v\""
+        echo "!!! failed to remove \"attribute_$v\""
         exit 1
     fi
     
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -152,14 +152,14 @@ AC_SUBST(libxfs)
 AC_SUBST(libhdl)
 
 dnl Checks for Extended Attributes header and library.
-AC_CHECK_HEADER(attr/attributes.h,, [
+AC_CHECK_HEADER(attr/xattr.h,, [
 	echo
 	echo 'FATAL ERROR: could not find a valid Extended Attributes header.'
 	echo 'Install either the attr-devel (rpm) or the attr-dev (deb) package.'
 	echo 'Alternatively, run "make install-dev" from the attr source.'
 	exit 1
 ])
-AC_CHECK_LIB(attr, attr_get,, [
+AC_CHECK_LIB(attr, getxattr,, [
 	echo
 	echo 'FATAL ERROR: could not find a valid Extended Attributes library.'
 	echo 'Install either the attr-devel (rpm) or the attr-dev (deb) package.'
@@ -169,19 +169,26 @@ AC_CHECK_LIB(attr, attr_get,, [
 libattr="-lattr"
 AC_SUBST(libattr)
 
-dnl Checks for Access Control List header and library.
+dnl Checks for Access Control List headers and library.
 AC_CHECK_HEADER(sys/acl.h,, [
 	echo
-	echo 'FATAL ERROR: could not find a valid Access Control List header.'
-	echo 'Install either the acl-devel (rpm) or the acl-dev (deb) package.'
-	echo 'Alternatively, run "make install-dev" from the acl source.'
+	echo 'FATAL ERROR: could not find a valid Access Control List headers.'
+	echo 'Install either the acl-devel (rpm) or the acl (deb) package.'
+	echo 'Alternatively, run "make install" from the acl source.'
+	exit 1
+])
+AC_CHECK_HEADER(acl/libacl.h,, [
+	echo
+	echo 'FATAL ERROR: could not find a valid Access Control List headers.'
+	echo 'Install either the acl-devel (rpm) or the acl (deb) package.'
+	echo 'Alternatively, run "make install" from the acl source.'
 	exit 1
 ])
 AC_CHECK_LIB(acl, acl_init,, [
 	echo
 	echo 'FATAL ERROR: could not find a valid Access Control List library.'
-	echo 'Install either the acl-devel (rpm) or the acl-dev (deb) package.'
-	echo 'Alternatively, run "make install-dev" from the acl source.'
+	echo 'Install either the acl-devel (rpm) or the acl (deb) package.'
+	echo 'Alternatively, run "make install" from the acl source.'
 	exit 1
 ])
 libacl="-lacl"
