test 032: Run mkfs.xfs only if the prior mkfs.${fs} succeded
This test fails when mkfs of a different filesystem fails, which is not
a failure case for this specific test.

Hence, change the test to run mkfs.xfs only if the prior mkfs.${fs} on
different filesystem succeded.

Signed-off-by: Chandra Seetharaman <sekharan@us.ibm.com>
Signed-off-by: Christoph Hellwig <hch@lst.de>

diff --git a/032 b/032
--- a/032
+++ b/032
@@ -75,11 +75,15 @@ do
 	echo "    ( $preop mkfs -t $fs $preargs $SCRATCH_DEV $postargs )" >>$seq.full
 	eval $preop mkfs -t $fs $preargs $SCRATCH_DEV $postargs >>$seq.full 2>&1
 
-	# next, ensure we don't overwrite it
-	echo "=== Attempting XFS overwrite of $fs..." >>$seq.full
-	/sbin/mkfs.xfs $SCRATCH_DEV >>$seq.full 2>&1
+	if [ $? -eq 0 ] ; then
+		# next, ensure we don't overwrite it
+		echo "=== Attempting XFS overwrite of $fs..." >>$seq.full
+		/sbin/mkfs.xfs $SCRATCH_DEV >>$seq.full 2>&1
 
-	[ $? -eq 0 ] && echo "Failed - overwrote fs type ${fs}!"
+		[ $? -eq 0 ] && echo "Failed - overwrote fs type ${fs}!"
+	else
+		echo "mkfs of type ${fs} failed" >>$seq.full
+	fi
 done
 
 # success, all done
