QA source updates and some associated test changes

diff --git a/034 b/034
--- a/034
+++ b/034
@@ -2,7 +2,7 @@
 # XFS QA Test No. 034
 # $Id: 1.1 $
 #
-# pv 801241 - check for reference leaks from the *handle ioctls
+# pv 801241 - check for reference leaks from the *handle xfsctls
 #
 #-----------------------------------------------------------------------
 # Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
@@ -82,9 +82,9 @@ then
     exit
 fi
 
-if ! src/ioctl $SCRATCH_MNT $SCRATCH_MNT/fish >/dev/null 2>&1
+if ! src/xfsctl $SCRATCH_MNT $SCRATCH_MNT/fish >/dev/null 2>&1
 then
-    echo "!!! failed to run ioctl test program"
+    echo "!!! failed to run xfsctl test program"
     exit
 fi
 
