Make test 040 less verbose since only I need to know this; integrate some old IRIX performance unit tests - metaperf and dirperf

diff --git a/040 b/040
--- a/040
+++ b/040
@@ -36,7 +36,7 @@
 #-----------------------------------------------------------------------
 #
 # creator
-owner=dxm@sgi.com
+owner=nathans@sgi.com
 
 seq=`basename $0`
 echo "QA output created by $seq"
@@ -74,8 +74,13 @@ then
     _notrun "Can't find XFS command headers under \"$WORKAREA\""
 fi
 
-cd $WORKAREA/cmd/xfstests/tools
-perl ./srcdiff -q
+cd $WORKAREA/cmd/xfstests
+echo Silence is golden.
+perl tools/srcdiff -q >$seq.full
+if ! diff $seq.full $seq.good >/dev/null; then
+    echo "FAILED: srcdiff output $seq.full differs to $seq.good"
+    exit 1
+fi
 
 # success, all done
 status=0
