QA test updates - fixes for pquota, extsize, fsstress, and ensure mount options passed through to test_dev. Merge of master-melb:xfs-cmds:24763a by kenmcd.

diff --git a/075 b/075
--- a/075
+++ b/075
@@ -65,8 +65,10 @@ _do_test()
     cd $out
     if ! $here/ltp/fsx $_param -P $here $seq.$_n >/dev/null
     then
-	echo "    fsx ($_param) returned $? - see $seq.$_n.full"
-	mv $seq.$_n.fsxlog $here/$seq.$_n.full
+	echo "    fsx ($_param) failed, $? - compare $seq.$_n.{good,bad,fsxlog}"
+	mv $out/$seq.$_n $here/$seq.$_n.full
+	od -xAx $here/$seq.$_n.full > $here/$seq.$_n.bad
+	od -xAx $here/$seq.$_n.fsxgood > $here/$seq.$_n.good
 	status=1
 	exit
     fi
