xfstests update - Ethans new inode flags test mainly

diff --git a/079 b/079
--- a/079
+++ b/079
@@ -1,4 +1,9 @@
-# 
+#! /bin/sh
+# XFS QA Test No. 079
+#
+# Run the t_immutable test program for immutable/append-only files.
+#
+#-----------------------------------------------------------------------
 # Copyright (c) 2000-2003 Silicon Graphics, Inc.  All Rights Reserved.
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -28,54 +33,39 @@
 # For further information regarding this notice, see: 
 # 
 # http://oss.sgi.com/projects/GenInfo/SGIGPLNoticeExplan/
+#-----------------------------------------------------------------------
 #
+# creator
+owner=nathans@sgi.com
 
-TOPDIR = ..
-include $(TOPDIR)/include/builddefs
+seq=`basename $0`
+echo "QA output created by $seq"
 
-TARGETS = alloc acl_get bstat devzero dirstress fault feature \
-	  fill fill2 getpagesize holes xfsctl loggen lstat64 \
-	  nametest permname randholes runas truncfile usemem \
-	  fstest mmapcat append_reader append_writer \
-	  dirperf metaperf
-ifeq ($(ENABLE_DBM), yes)
-TARGETS += dbtest
-endif
-ifeq ($(PKG_PLATFORM),linux)
-TARGETS += t_immutable
-endif
+here=`pwd`
+timmutable=$here/src/t_immutable
+tmp=/tmp/$$
+status=1	# failure is the default!
+trap "_cleanup; exit \$status" 0 1 2 3 15
 
-CFILES = $(TARGETS:=.c)
-LDIRT = $(TARGETS)
+_cleanup()
+{
+    echo "*** cleaning up"
+    $timmutable -r $SCRATCH_MNT/$seq
+    umount $SCRATCH_MNT
+}
 
-default: $(TARGETS)
+# get standard environment, filters and checks
+. ./common.rc
+. ./common.filter
 
-include $(BUILDRULES)
-LINKTEST = $(LTLINK) $@.c -o $@ $(CFLAGS) $(LDFLAGS)
+_require_scratch
+[ -x $timmutable ] || _notrun "t_immutable was not built for this platform"
 
-randholes: randholes.o $(LIBTEST)
-	$(LINKTEST) $(LIBTEST) $(LDLIBS)
+# real QA test starts here
+_scratch_mkfs_xfs 2>&1 >/dev/null || _fail "mkfs failed"
+_scratch_mount || _fail "mount failed"
 
-truncfile: truncfile.o $(LIBTEST)
-	$(LINKTEST) $(LIBTEST) $(LDLIBS)
-
-dbtest:	dbtest.o $(LIBTEST)
-	$(LINKTEST) $(LIBTEST) $(LIBGDBM) $(LDLIBS)
-
-nametest: nametest.o $(LIBTEST)
-	$(LINKTEST) $(LIBTEST) $(LDLIBS)
-
-bstat: bstat.o $(LIBHANDLE)
-	$(LINKTEST) $(LIBHANDLE) $(LDLIBS)
-
-t_immutable: t_immutable.o $(LIBHANDLE) $(LIBACL)
-	$(LINKTEST) $(LIBACL) $(LIBHANDLE) $(LDLIBS)
-
-loggen:	loggen.o
-	$(LINKTEST) $(LDLIBS)
-
-fstest:	fstest.o
-	$(LINKTEST)
-
-acl_get: acl_get.o $(LIBACL) $(LIBATTR)
-	$(LINKTEST) $(LIBACL) $(LIBATTR) $(LDLIBS)
+echo "*** starting up"
+$timmutable -c $SCRATCH_MNT/$seq
+status=$?
+exit
