Integrate dmapi suite 1 into xfsqa infrastructure Merge of master-melb:xfs-cmds:27924a by kenmcd.
  added IRIX to _supported_os

diff --git a/159 b/159
--- a/159
+++ b/159
@@ -1,7 +1,7 @@
 #! /bin/sh
-# FSQA Test No. 142
+# FSQA Test No. 159
 #
-# Dmapi get/set_region
+# Create DMAPI event and respond to it.
 #
 #-----------------------------------------------------------------------
 #  Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
@@ -36,10 +36,22 @@ _require_scratch
 _scratch_mkfs_xfs >/dev/null 2>&1
 _dmapi_scratch_mount
 
-mkdir -p $SCRATCH_MNT/dmapi
+echo "***create session"
+eval `${DMAPI_QASUITE1_DIR}../simple/dm_create_session`
 
-# run DMAPI test using verbose output
-${DMAPI_QASUITE2_DIR}src/test_region -v $DMAPI_LS_TO_COPY_PATH $SCRATCH_MNT
+echo "***create user event"
+token="`${DMAPI_QASUITE1_DIR}cmd/create_userevent -s $newsid TEST_USER_EVENT | perl -ne 'if (/token ([0-9]+)/) { print $1; } '`"
+[ $? -ne 0 ] && echo "failed to create user event"
+
+echo "***respond to user event"
+${DMAPI_QASUITE1_DIR}cmd/respond_event $newsid $token 1 0
+[ $? -ne 0 ] && echo "1st respond_event failed."
+
+#already responded should fail
+${DMAPI_QASUITE1_DIR}cmd/respond_event $newsid $token 1 0 2>/dev/null
+[ $? -eq 0 ] && echo "2nd respond_event didn't fail."
+
+${DMAPI_QASUITE1_DIR}../simple/dm_destroy_session -s $newsid
 
 status=0
 exit 
