xfsqa: test 214 leaves files around that cause 236 to fail
Test 214 and 236 use the same file names for test files in the TEST
filesystem and don't check/create clean initial test state. Hence if
you run 214 then 236, 236 will fail with:

+link: cannot create link `/mnt/test/ouch2' to `/mnt/test/ouch': File exists
+ctime: 1277076527 -> 1277076527 
+Fatal error: ctime not updated after link

Ensure that both tests clean up after themselves properly and also
ensure a clean state before they start.

Signed-off-by: Dave Chinner <dchinner@redhat.com>
Reviewed-by: Christoph Hellwig <hch@lst.de>

diff --git a/236 b/236
--- a/236
+++ b/236
@@ -30,15 +30,12 @@ echo "QA output created by $seq"
 
 _cleanup()
 {
-	if [ -a $TEST_DIR/ouch2 ]; then
-		rm -f $TEST_DIR/ouch2
-	fi
-	if [ -a $TEST_DIR/ouch ]; then
-		rm -f $TEST_DIR/ouch
-	fi
+	rm -f $TEST_DIR/ouch*
 }
 
 here=`pwd`
+status=1	# failure is the default!
+trap "_cleanup; exit \$status" 0 1 2 3 15
 
 # get standard environment, filters and checks
 . ./common.rc
@@ -47,6 +44,8 @@ here=`pwd`
 _supported_fs generic
 # only Linux supports fallocate
 _supported_os Linux
+
+rm -f $TEST_DIR/ouch*
 
 # create a file and get its ctime
 touch $TEST_DIR/ouch
@@ -64,8 +63,6 @@ if [ $ctime2 -le $ctime ]; then
 	_cleanup
 	exit 1
 fi
-
-_cleanup
 
 echo "Test over."
 # success, all done
