xfstests: RESULTS_DIR needs to be an absolute path
Some tests 'cd <somedir>' and then direct output to $RESULT_DIR,
which fails if the current working directory is not $here.
Regardless, if an external results directory is to be used it needs
to have a full path specified and the use of $here as the base of
the results files is completely incorrect.

Hence change all the $here/$seqres* references to simply be
$seqres*, and instead encode the full path to the results in
$RESULT_DIR.

Signed-off-by: Dave Chinner <dchinner@redhat.com>
Reviewed-by: Phil White <pwhite@sgi.com>
Signed-off-by: Rich Johnston <rjohnston@sgi.com>

diff --git a/check b/check
--- a/check
+++ b/check
@@ -36,24 +36,37 @@ here=`pwd`
 FSTYP=xfs
 xfile=""
 
-SUPPORTED_TESTS="[0-9][0-9][0-9] [0-9][0-9][0-9][0-9]"
-SRC_GROUPS="generic shared"
-export SRC_DIR="tests"
-export RESULT_BASE=${RESULT_BASE:="results"}
-
-# generic initialization
+# start the initialisation work now
 iam=check
 
+export MSGVERB="text:action"
 export QA_CHECK_FS=${QA_CHECK_FS:=true}
-
-# by default don't output timestamps
-timestamp=${TIMESTAMP:=false}
 
 # number of diff lines from a failed test, 0 for whole output
 export DIFF_LENGTH=${DIFF_LENGTH:=10}
 
 # by default don't output timestamps
 timestamp=${TIMESTAMP:=false}
+
+rm -f $tmp.list $tmp.tmp $tmp.grep $here/$iam.out $tmp.xlist
+
+# Autodetect fs type based on what's on $TEST_DEV
+if [ "$HOSTOS" == "Linux" ]; then
+    FSTYP=`blkid -c /dev/null -s TYPE -o value $TEST_DEV`
+fi
+export FSTYP
+
+# we need common.config
+if ! . ./common/config
+then
+    echo "$iam: failed to source common/config"
+    exit 1
+fi
+
+SUPPORTED_TESTS="[0-9][0-9][0-9] [0-9][0-9][0-9][0-9]"
+SRC_GROUPS="generic shared"
+export SRC_DIR="tests"
+export RESULT_BASE=${RESULT_BASE:="$here/results"}
 
 usage()
 {
@@ -77,12 +90,6 @@ testlist options
     [testlist]		include tests matching names in testlist
 '
 	    exit 0
-}
-
-_setenvironment()
-{
-    MSGVERB="text:action"
-    export MSGVERB
 }
 
 get_group_list()
@@ -146,24 +153,6 @@ _timestamp()
     now=`date "+%T"`
     echo -n " [$now]"
 }
-
-# start the initialisation work now
-_setenvironment
-
-rm -f $tmp.list $tmp.tmp $tmp.grep $here/$iam.out $tmp.xlist
-
-# Autodetect fs type based on what's on $TEST_DEV
-if [ "$HOSTOS" == "Linux" ]; then
-    FSTYP=`blkid -c /dev/null -s TYPE -o value $TEST_DEV`
-fi
-export FSTYP
-
-# we need common.config
-if ! . ./common/config
-then
-    echo "$iam: failed to source common/config"
-    exit 1
-fi
 
 # Process command arguments first.
 while [ $# -gt 0 ]; do
diff --git a/tests/generic/075 b/tests/generic/075
--- a/tests/generic/075
+++ b/tests/generic/075
@@ -80,10 +80,10 @@ _do_test()
     cd $out
     if ! $here/ltp/fsx $_param -P $here $seq.$_n &>/dev/null
     then
-	echo "    fsx ($_param) failed, $? - compare $seq.$_n.{good,bad,fsxlog}"
-	mv $out/$seq.$_n $here/$seq.$_n.full
-	od -xAx $here/$seq.$_n.full > $here/$seq.$_n.bad
-	od -xAx $here/$seq.$_n.fsxgood > $here/$seq.$_n.good
+	echo "    fsx ($_param) failed, $? - compare $seqres.$_n.{good,bad,fsxlog}"
+	mv $out/$seq.$_n $seqres.$_n.full
+	od -xAx $seqres.$_n.full > $seqres.$_n.bad
+	od -xAx $seqres.$_n.fsxgood > $seqres.$_n.good
 	status=1
 	exit
     fi
@@ -141,7 +141,7 @@ echo "Params: n = $numops1 N = $numops2 l = $filelen" >>$seqres.full
 
 _setup_testdir
 
-rm -f $here/$seqres.full
+rm -f $seqres.full
 echo "brevity is wit..."
 
 _check_test_fs
