Fixed general IRIX/Linux problems when running the -udf option. Changed specific _scratch_xfs_mkfs to general _scratch_mkfs call.

diff --git a/check b/check
--- a/check
+++ b/check
@@ -171,14 +171,14 @@ MOUNT_OPTIONS -- $FULL_MOUNT_OPTIONS
 EOF
 
 umount $SCRATCH_DEV 2>/dev/null
-# call the overridden mkfs.xfs - make sure the FS is built
+# call the overridden mkfs - make sure the FS is built
 # the same as we'll create it later.
 
-if ! _scratch_mkfs_xfs $flag >$tmp.err 2>&1
+if ! _scratch_mkfs $flag >$tmp.err 2>&1
 then
-    echo "our local _scratch_mkfs_xfs routine ..."
+    echo "our local _scratch_mkfs routine ..."
     cat $tmp.err
-    echo "check: failed to mkfs.xfs \$SCRATCH_DEV using specified options"
+    echo "check: failed to mkfs \$SCRATCH_DEV using specified options"
     exit 1
 fi
 
