xfstests: introduce a common directory
Introduce a top level common directory and move all the common.*
files into it.  Because there is now a directory named common, the
prefix can be dropped from all the files. Convert all the tests to
use this new directory for including common files.

for f in common.*; do \
	git mv `echo -n "$f " ; echo $f | sed -e 's;n\.;n/;'` \
done

Signed-off-by: Dave Chinner <dchinner@redhat.com>
Reviewed-by: Phil White <pwhite@sgi.com>
[rjohnston@sgi.com reworked for TOT changes]
Signed-off-by: Rich Johnston <rjohnston@sgi.com>

diff --git a/check b/check
--- a/check
+++ b/check
@@ -133,9 +133,9 @@ fi
 export FSTYP
 
 # we need common.config
-if ! . ./common.config
+if ! . ./common/config
 then
-    echo "$iam: failed to source common.config"
+    echo "$iam: failed to source common/config"
     exit 1
 fi
 
@@ -266,10 +266,10 @@ then
     list=`echo $list | awk -f randomize.awk`
 fi
 
-# we need common.rc
-if ! . ./common.rc
+# we need common/rc
+if ! . ./common/rc
 then
-    echo "check: failed to source common.rc"
+    echo "check: failed to source common/rc"
     exit 1
 fi
 
