The test device is now used as a nfs filesystem. Merge of master-melb:xfs-cmds:26462a by kenmcd.
  modified this test to run on xfs only.

diff --git a/check b/check
--- a/check
+++ b/check
@@ -2,7 +2,7 @@
 #
 # Control script for QA
 #
-# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
+# Copyright (c) 2000-2002,2006 Silicon Graphics, Inc.  All Rights Reserved.
 #
 
 tmp=/tmp/$$
@@ -16,8 +16,24 @@ interrupt=true
 
 export QA_CHECK_FS=${QA_CHECK_FS:=true}
 
+# by default don't output timestamps
+timestamp=${TIMESTAMP:=false}
+
 # generic initialization
 iam=check
+
+# we need common.config
+if ! . ./common.config
+then
+    echo "$iam: failed to source common.config"
+    exit 1
+fi
+
+# we need common
+. ./common
+
+
+# we need common.rc
 if ! . ./common.rc
 then
     echo "check: failed to source common.rc"
@@ -121,11 +137,6 @@ echo "preamble" >/tmp/check.sts
 
 # don't leave old full output behind on a clean run
 rm -f check.full
-
-# by default don't output timestamps
-timestamp=${TIMESTAMP:=false}
-
-. ./common
 
 [ -f check.time ] || touch check.time
 
