xfstests: fix common source file path
After the re-factor, common.* have been renamed to common/* but there
are several files still look for the old path, fix it.

Signed-off-by: Eryu Guan <eguan@redhat.com>
Reviewed-by: Rich Johnston <rjohnston@sgi.com>
Signed-off-by: Rich Johnston <rjohnston@sgi.com>

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -15,9 +15,9 @@
 # along with this program; if not, write the Free Software Foundation,
 # Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 #
-if ! . ./common.config
+if ! . ./common/config
 then
-    echo "check: failed to source common.config"
+    echo "check: failed to source common/config"
     exit 1
 fi
 
