xfstests: convert tests to use new results directory
Essentially the change is simply this. Converting:

... >> $seq.????

to:

.... >> $RESULT_DIR/$seq.????

so that output files are directed to the defined output directory.

sed to the rescue:

$ sed -i -e '/^seq=.*$/a seqres=$RESULT_DIR/$seq' -e 's/seq.full/seqres.full/' tests/*/*

will do most of the work automatically.

Signed-off-by: Dave Chinner <dchinner@redhat.com>
Reviewed-by: Phil White <pwhite@sgi.com>
[rjohnston@sgi.com reworked for TOT changes]
Signed-off-by: Rich Johnston <rjohnston@sgi.com>

diff --git a/tests/xfs/040 b/tests/xfs/040
--- a/tests/xfs/040
+++ b/tests/xfs/040
@@ -23,6 +23,9 @@
 #
 
 seq=`basename $0`
+seqres=$RESULT_DIR/$seq
+seqres=$RESULT_DIR/$seq
+seqres=$RESULT_DIR/$seq
 echo "QA output created by $seq"
 
 here=`pwd`
@@ -49,9 +52,9 @@ trap "rm -f $tmp.*; exit \$status" 0 1 2 3 15
 # real QA test starts here
 cd "$WORKAREA/xfstests"
 echo Silence is golden.
-perl tools/srcdiff -q >$seq.full
-if ! diff $seq.full $seq.good >/dev/null; then
-    echo "FAILED: srcdiff output $seq.full differs to $seq.good"
+perl tools/srcdiff -q >$seqres.full
+if ! diff $seqres.full $seq.good >/dev/null; then
+    echo "FAILED: srcdiff output $seqres.full differs to $seq.good"
     exit 1
 fi
 
