filter: inode size output of mkfs.xfs can change
With the change to CRCs by default, the mkfs inode size is defaults
to 512 bytes and the minimum block size changes to 1024 bytes. This
causes mismatches with golden output that expects the inode size to
be 256 bytes, and some tests are tailored around the amount of space
inside a 256 byte inode. Fix them with appropriate filtering or mkfs
parameters to allow 256 byte inodes to be used.

Signed-off-by: Dave Chinner <dchinner@redhat.com>
Signed-off-by: Dave Chinner <david@fromorbit.com>

diff --git a/tests/xfs/259 b/tests/xfs/259
--- a/tests/xfs/259
+++ b/tests/xfs/259
@@ -37,6 +37,7 @@ trap "_cleanup ; exit \$status" 0 1 2 3 15
 
 # get standard environment, filters and checks
 . ./common/rc
+. ./common/filter
 
 # real QA test starts here
 _supported_fs xfs
@@ -47,9 +48,22 @@ _require_math
 
 testfile=$TEST_DIR/259.image
 
-# Test various sizes slightly less than 4 TB
+# Test various sizes slightly less than 4 TB. Need to handle different
+# minimum block sizes for CRC enabled filesystems, but use a small log so we
+# don't write lots of zeros unnecessarily.
+xfs_info $TEST_DIR | _filter_mkfs 2> $tmp.mkfs > /dev/null
+. $tmp.mkfs
+if [ $_fs_has_crcs -eq 1 ]; then
+	blocksize=1024
+	sizes_to_check="1024 2048 4096"
+	echo "Trying to make (4 TB - 512) B long xfs fs image"
+else
+	blocksize=512
+	sizes_to_check="512 1024 2048 4096"
+fi
+
 four_TB=$(_math "2^42")
-for del in 512 1024 2048 4096; do
+for del in $sizes_to_check; do
 	ddseek=$(_math "$four_TB - $del")
 	echo "Trying to make (4 TB - $del) B long xfs fs image"
 	rm -f "$testfile"
@@ -57,7 +71,8 @@ for del in 512 1024 2048 4096; do
 					>/dev/null 2>&1 || echo "dd failed"
 	lofile=$(losetup -f)
 	losetup $lofile "$testfile"
-	"$MKFS_XFS_PROG" -b size=512 $lofile >/dev/null || echo "mkfs failed!"
+	"$MKFS_XFS_PROG" -l size=32m -b size=$blocksize $lofile \
+					>/dev/null || echo "mkfs failed!"
 	sync
 	losetup -d $lofile
 done
